/// Checks this port against reference vectors extracted from the upstream
/// JavaScript blobatar.
///
/// The fixture is generated by running upstream, never by recording what this
/// port produces — see tool/extract_upstream_vectors.ts. Recording our own
/// output would make the library's central promise check itself.
///
/// Comparisons are exact. Both languages compute in IEEE-754 doubles over the
/// same operations in the same order, so "close enough" would only hide a real
/// divergence; every number here either matches bit for bit or is a bug.
library;

import 'dart:convert';
import 'dart:io';

import 'package:blobatar_flutter/src/color.dart';
import 'package:blobatar_flutter/src/pose.dart';
import 'package:blobatar_flutter/src/styles/layout.dart';
import 'package:blobatar_flutter/src/traits.dart';
import 'package:flutter/painting.dart';
import 'package:flutter_test/flutter_test.dart';

String _hex(Color c) =>
    '#${(c.toARGB32() & 0xFFFFFF).toRadixString(16).padLeft(6, '0')}';

void main() {
  final fixture = jsonDecode(
    File('test/fixtures/upstream_gen2.json').readAsStringSync(),
  ) as Map<String, dynamic>;
  final meta = fixture['meta'] as Map<String, dynamic>;
  final cases = (fixture['cases'] as List).cast<Map<String, dynamic>>();

  test('fixture is the one we think it is', () {
    expect(meta['generation'], 'gen2');
    expect(cases, hasLength(greaterThan(300)));
    // Every silhouette must be exercised: the band table is weighted, so the
    // rare ones would otherwise slip through on a handful of samples.
    final shapes = meta['shapes'] as Map<String, dynamic>;
    expect(shapes.keys.toSet(), BlobShape.values.map((s) => s.name).toSet());
    for (final entry in shapes.entries) {
      expect(entry.value, greaterThanOrEqualTo(25),
          reason: '${entry.key} under-sampled',);
    }
  });

  group('layout matches upstream ${meta['version']}', () {
    for (final c in cases) {
      final seed = c['seed'] as String;
      test('$seed (${c['shape']})', () {
        final t = Traits(seed);
        final l = computeLayout(t);

        expect(l.shape.name, c['shape'], reason: 'silhouette');

        final b = c['body'] as Map<String, dynamic>;
        expect(l.body.cx, b['cx'], reason: 'body.cx');
        expect(l.body.cy, b['cy'], reason: 'body.cy');
        expect(l.body.rx, b['rx'], reason: 'body.rx');
        expect(l.body.ry, b['ry'], reason: 'body.ry');
        expect(l.body.n, b['n'], reason: 'body.n');
        expect(l.body.rot, b['rot'], reason: 'body.rot');
        expect(l.body.radii, b['radii'], reason: 'body.radii');
        expect(l.body.sides, b['sides'], reason: 'body.sides');
        expect(l.body.round, b['round'], reason: 'body.round');

        final f = c['face'] as Map<String, dynamic>;
        expect(l.face.cx, f['cx'], reason: 'face.cx');
        expect(l.face.cy, f['cy'], reason: 'face.cy');
        expect(l.face.rx, f['rx'], reason: 'face.rx');
        expect(l.face.ry, f['ry'], reason: 'face.ry');

        final eyes = (c['eyes'] as List).cast<Map<String, dynamic>>();
        expect(l.eyes, hasLength(eyes.length));
        for (var i = 0; i < eyes.length; i++) {
          expect(l.eyes[i].cx, eyes[i]['cx'], reason: 'eyes[$i].cx');
          expect(l.eyes[i].cy, eyes[i]['cy'], reason: 'eyes[$i].cy');
          expect(l.eyes[i].rx, eyes[i]['rx'], reason: 'eyes[$i].rx');
          expect(l.eyes[i].ry, eyes[i]['ry'], reason: 'eyes[$i].ry');
          expect(l.eyes[i].n, eyes[i]['n'], reason: 'eyes[$i].n');
          expect(l.eyes[i].rot, eyes[i]['rot'], reason: 'eyes[$i].rot');
        }

        final petals = (c['petals'] as List).cast<Map<String, dynamic>>();
        expect(l.petals, hasLength(petals.length), reason: 'petal count');
        for (var i = 0; i < petals.length; i++) {
          expect(l.petals[i].cx, petals[i]['cx'], reason: 'petals[$i].cx');
          expect(l.petals[i].cy, petals[i]['cy'], reason: 'petals[$i].cy');
          expect(l.petals[i].r, petals[i]['r'], reason: 'petals[$i].r');
        }
        expect(l.extra, hasLength(c['extra']), reason: 'extra outline count');
      });
    }
  });

  group('palette matches upstream ${meta['version']}', () {
    for (final c in cases) {
      final seed = c['seed'] as String;
      test(seed, () {
        final t = Traits(seed);
        final hue = t.num('hue', 0, 360);
        expect(hue, c['hue'], reason: 'hue');
        expect(t('tone'), c['tone'], reason: 'tone');

        final p = buildPalette(hue, tone: t('tone'));
        final jp = c['palette'] as Map<String, dynamic>;
        expect(_hex(p.bg), jp['bg'], reason: 'bg');
        expect(_hex(p.head), jp['head'], reason: 'head');
        expect(_hex(p.eye), jp['eye'], reason: 'eye');
      });
    }
  });

  group('expression poses match upstream ${meta['version']}', () {
    final upstream = fixture['expressions'] as Map<String, dynamic>;

    test('every upstream expression exists here', () {
      expect(expressions.keys.toSet(), upstream.keys.toSet());
    });

    for (final entry in upstream.entries) {
      test('${entry.key} pose', () {
        final p = expressions[entry.key]!.pose;
        final u = entry.value as Map<String, dynamic>;
        expect(p.esx, u['esx']);
        expect(p.esy, u['esy']);
        expect(p.tilt, u['tilt']);
        expect(p.edy, u['edy']);
        expect(p.edx, u['edx']);
        expect(p.esx2, u['esx2']);
        expect(p.esy2, u['esy2']);
        expect(p.tilt2, u['tilt2']);
        expect(p.edy2, u['edy2']);
        expect(p.lock, u['lock']);
        expect(p.heat, u['heat']);
        expect(p.shake, u['shake']);
        expect(p.rock, u['rock']);
        expect(p.bdy, u['bdy']);
      });
    }
  });
}
