/// Checks this port against reference vectors extracted from the upstream
/// JavaScript blobatar.
///
/// The fixture is generated by running upstream, never by recording what this
/// port produces — see tool/extract_upstream_vectors.ts. Recording our own
/// output would make the library's central promise check itself.
///
/// Comparisons are exact, with one deliberate exception: layout geometry
/// (`body`, `face`, `eyes`, `petals`) allows the platform floating-point
/// noise `dart:math`'s `cos`/`sin`/`atan2`/`pow` can introduce — see the
/// README's "Caveat: `dart:math` trig across platforms". Everywhere else,
/// "close enough" would only hide a real divergence; every other number here
/// either matches bit for bit or is a bug.
library;

import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:blobatar_flutter/src/color.dart';
import 'package:blobatar_flutter/src/pose.dart';
import 'package:blobatar_flutter/src/styles/layout.dart';
import 'package:blobatar_flutter/src/traits.dart';
import 'package:flutter/painting.dart';
import 'package:flutter_test/flutter_test.dart';

String _hex(Color c) =>
    '#${(c.toARGB32() & 0xFFFFFF).toRadixString(16).padLeft(6, '0')}';

/// True within the platform trig noise described up top — not a general
/// "close enough". 1e-9 relative is many orders above the ~1e-15-relative
/// gap that noise actually produces, and many orders below anything a real
/// divergence in the algorithm would leave.
bool _closeEnough(num a, num b) {
  if (a == b) return true;
  final scale = math.max(a.abs(), b.abs());
  return (a - b).abs() <= scale * 1e-9;
}

/// Like `expect(actual, expected, reason: reason)`, but for a layout field
/// that may carry platform trig noise. Null on either side falls back to
/// exact equality, since `_closeEnough` only makes sense between two numbers.
void _expectClose(double? actual, dynamic expected, String reason) {
  final e = expected as num?;
  if (actual == null || e == null) {
    expect(actual, e, reason: reason);
    return;
  }
  expect(_closeEnough(actual, e), isTrue,
      reason: '$reason: expected ~$e, got $actual',);
}

void main() {
  final fixture = jsonDecode(
    File('test/fixtures/upstream_gen2.json').readAsStringSync(),
  ) as Map<String, dynamic>;
  final meta = fixture['meta'] as Map<String, dynamic>;
  final cases = (fixture['cases'] as List).cast<Map<String, dynamic>>();

  test('fixture is the one we think it is', () {
    expect(meta['generation'], 'gen2');
    expect(cases, hasLength(greaterThan(300)));
    // Every silhouette must be exercised: the band table is weighted, so the
    // rare ones would otherwise slip through on a handful of samples.
    final shapes = meta['shapes'] as Map<String, dynamic>;
    expect(shapes.keys.toSet(), BlobShape.values.map((s) => s.name).toSet());
    for (final entry in shapes.entries) {
      expect(entry.value, greaterThanOrEqualTo(25),
          reason: '${entry.key} under-sampled',);
    }
  });

  group('layout matches upstream ${meta['version']}', () {
    for (final c in cases) {
      final seed = c['seed'] as String;
      test('$seed (${c['shape']})', () {
        final t = Traits(seed);
        final l = computeLayout(t);

        expect(l.shape.name, c['shape'], reason: 'silhouette');

        final b = c['body'] as Map<String, dynamic>;
        _expectClose(l.body.cx, b['cx'], 'body.cx');
        _expectClose(l.body.cy, b['cy'], 'body.cy');
        _expectClose(l.body.rx, b['rx'], 'body.rx');
        _expectClose(l.body.ry, b['ry'], 'body.ry');
        _expectClose(l.body.n, b['n'], 'body.n');
        _expectClose(l.body.rot, b['rot'], 'body.rot');
        final radii = (b['radii'] as List).cast<num>();
        expect(l.body.radii, hasLength(radii.length), reason: 'body.radii');
        for (var i = 0; i < radii.length; i++) {
          _expectClose(l.body.radii[i], radii[i], 'body.radii[$i]');
        }
        // Polygon-only, and an integer: never touches cos/sin/atan2/pow.
        expect(l.body.sides, b['sides'], reason: 'body.sides');
        _expectClose(l.body.round, b['round'], 'body.round');

        final f = c['face'] as Map<String, dynamic>;
        _expectClose(l.face.cx, f['cx'], 'face.cx');
        _expectClose(l.face.cy, f['cy'], 'face.cy');
        _expectClose(l.face.rx, f['rx'], 'face.rx');
        _expectClose(l.face.ry, f['ry'], 'face.ry');

        final eyes = (c['eyes'] as List).cast<Map<String, dynamic>>();
        expect(l.eyes, hasLength(eyes.length));
        for (var i = 0; i < eyes.length; i++) {
          _expectClose(l.eyes[i].cx, eyes[i]['cx'], 'eyes[$i].cx');
          _expectClose(l.eyes[i].cy, eyes[i]['cy'], 'eyes[$i].cy');
          _expectClose(l.eyes[i].rx, eyes[i]['rx'], 'eyes[$i].rx');
          _expectClose(l.eyes[i].ry, eyes[i]['ry'], 'eyes[$i].ry');
          _expectClose(l.eyes[i].n, eyes[i]['n'], 'eyes[$i].n');
          _expectClose(l.eyes[i].rot, eyes[i]['rot'], 'eyes[$i].rot');
        }

        final petals = (c['petals'] as List).cast<Map<String, dynamic>>();
        expect(l.petals, hasLength(petals.length), reason: 'petal count');
        for (var i = 0; i < petals.length; i++) {
          _expectClose(l.petals[i].cx, petals[i]['cx'], 'petals[$i].cx');
          _expectClose(l.petals[i].cy, petals[i]['cy'], 'petals[$i].cy');
          _expectClose(l.petals[i].r, petals[i]['r'], 'petals[$i].r');
        }
        expect(l.extra, hasLength(c['extra']), reason: 'extra outline count');
      });
    }
  });

  group('palette matches upstream ${meta['version']}', () {
    for (final c in cases) {
      final seed = c['seed'] as String;
      test(seed, () {
        final t = Traits(seed);
        final hue = t.num('hue', 0, 360);
        expect(hue, c['hue'], reason: 'hue');
        expect(t('tone'), c['tone'], reason: 'tone');

        final p = buildPalette(hue, tone: t('tone'));
        final jp = c['palette'] as Map<String, dynamic>;
        expect(_hex(p.bg), jp['bg'], reason: 'bg');
        expect(_hex(p.head), jp['head'], reason: 'head');
        expect(_hex(p.eye), jp['eye'], reason: 'eye');
      });
    }
  });

  group('expression poses match upstream ${meta['version']}', () {
    final upstream = fixture['expressions'] as Map<String, dynamic>;

    test('every upstream expression exists here', () {
      expect(expressions.keys.toSet(), upstream.keys.toSet());
    });

    for (final entry in upstream.entries) {
      test('${entry.key} pose', () {
        final p = expressions[entry.key]!.pose;
        final u = entry.value as Map<String, dynamic>;
        expect(p.esx, u['esx']);
        expect(p.esy, u['esy']);
        expect(p.tilt, u['tilt']);
        expect(p.edy, u['edy']);
        expect(p.edx, u['edx']);
        expect(p.esx2, u['esx2']);
        expect(p.esy2, u['esy2']);
        expect(p.tilt2, u['tilt2']);
        expect(p.edy2, u['edy2']);
        expect(p.lock, u['lock']);
        expect(p.heat, u['heat']);
        expect(p.shake, u['shake']);
        expect(p.rock, u['rock']);
        expect(p.bdy, u['bdy']);
      });
    }
  });
}
