/**
 * Extracts reference vectors from the upstream JavaScript blobatar.
 *
 * This package claims its output is identical to upstream's, seed for seed.
 * That claim is only worth something if it is checked against the real thing,
 * so the fixture in test/fixtures/ is generated by *running upstream*, never
 * by recording what this port happens to produce. Recording our own output
 * would turn the only check on the library's central promise into a tautology.
 *
 * Usage:
 *   git clone --depth 1 https://github.com/Alain00/blobatar /tmp/blobatar
 *   bun tool/extract_upstream_vectors.ts /tmp/blobatar > test/fixtures/upstream_gen2.json
 *
 * Requires bun, which is upstream's own package manager. A diff in the
 * generated fixture means either upstream changed generation (a new major on
 * their side) or this port drifted. Neither is fixed by regenerating without
 * reading the diff first.
 */
const root = process.argv[2];
if (!root) {
  console.error("usage: bun tool/extract_upstream_vectors.ts <path-to-upstream-clone>");
  process.exit(1);
}
/**
 * Upstream's eye fit calls `Math.hypot`, which is NOT bit-stable across
 * JavaScript engines: V8 (Chrome, Edge, Node) evaluates it as the scaled form
 * below, while JavaScriptCore — which Bun runs on, and Safari — uses a
 * correctly-rounded algorithm that disagrees by one unit in the last place on
 * roughly a third of inputs. Verified over 300k random pairs on both.
 *
 * That means upstream renders a few seeds one ULP apart depending on the
 * browser. The fixture has to pick one, so it picks the one most of
 * blobatar's users actually see, and says so rather than silently recording
 * whichever engine generated it.
 */
Math.hypot = ((...values: number[]) => {
  let max = 0;
  for (const v of values) { const a = Math.abs(v); if (a > max) max = a; }
  if (max === 0) return 0;
  let sum = 0;
  for (const v of values) { const n = v / max; sum += n * n; }
  return Math.sqrt(sum) * max;
}) as typeof Math.hypot;

const src = `${root}/packages/blobatar/src`;
const { traits } = await import(`${src}/traits.ts`);
const { layout } = await import(`${src}/blob.ts`);
const { palette } = await import(`${src}/color.ts`);
const expr = await import(`${src}/expression.ts`);
const pkg = await Bun.file(`${root}/packages/blobatar/package.json`).json();

/** Seed shapes chosen to exercise normalization, not just ASCII. */
const TEMPLATES: ((i: number) => string)[] = [
  i => `user-${i}`,
  i => `alain${i}@example.com`,
  i => `Team Rocket ${i}`,
  i => `café-${i}`,          // precomposed latin
  i => `café-${i}`,    // decomposed — must hash equal to the line above
  i => `Ünïcødé ${i}`,
  i => `🦊${i}🌱`,           // outside the BMP: surrogate pairs
  i => `${i}`,
  i => `  Mixed Case ${i}  `, // trim + lowercase
];

function record(seed: string) {
  const t = traits(seed);
  const l = layout(t);
  const hue = t.num("hue", 0, 360);
  const tone = t("tone");
  return {
    seed,
    shape: l.shape,
    body: l.body,
    face: l.face,
    eyes: l.eyes,
    petals: l.petals,
    extra: l.extra.length,
    hue,
    tone,
    palette: palette(hue, true, tone),
  };
}

const cases: ReturnType<typeof record>[] = [];
const seen = new Set<string>();
const add = (seed: string) => {
  if (seen.has(seed)) return;
  seen.add(seed);
  cases.push(record(seed));
};

// A baseline sweep across every seed shape.
for (let i = 0; i < 30; i++) for (const tpl of TEMPLATES) add(tpl(i));

// Then top up until every silhouette is represented. The band table is
// weighted, so triangle and sun would otherwise appear a handful of times in
// a sweep this size and the rare paths would go effectively unchecked.
const MIN_PER_SHAPE = 25;
const count = () => {
  const c: Record<string, number> = {};
  for (const k of cases) c[k.shape] = (c[k.shape] ?? 0) + 1;
  return c;
};
for (let i = 0; i < 200_000; i++) {
  const c = count();
  const shapes = Object.keys(c);
  if (shapes.length >= 10 && shapes.every(s => c[s]! >= MIN_PER_SHAPE)) break;
  const seed = `fill-${i}`;
  const t = traits(seed);
  const s = layout(t).shape;
  if ((c[s] ?? 0) < MIN_PER_SHAPE) add(seed);
}

const EXPRESSIONS = [
  "idle", "happy", "sad", "mad", "surprised", "wink", "sleepy", "smug",
  "unsure", "scared", "love", "shy", "sick", "thinking",
];
const poses: Record<string, unknown> = {};
for (const n of EXPRESSIONS) poses[n] = (expr as Record<string, { p: unknown }>)[n]!.p;

process.stdout.write(JSON.stringify({
  meta: {
    upstream: "https://github.com/Alain00/blobatar",
    version: pkg.version,
    generation: "gen2",
    mathHypot: "normalized to V8 semantics — see the note in this script",
    note: "Generated by tool/extract_upstream_vectors.ts. Do not hand-edit.",
    shapes: count(),
  },
  expressions: poses,
  cases,
}));
